### ISSUE TITLE
UnboundLocalError _ sskernel

### ISSUE THREAD

**Issue by Aryo-Zare** [shimazaki/AdaptiveKDE#12]
using your function : sskernel :
while anlyzing multiple data sessions I encountered the following problem :

```
Traceback (most recent call last):

  File "/home/azare/groups/PrimNeu/Aryo/analysis/fit/automate_mix_psth_fit_nmz_10_re_sig_8_unit_14_opt.py", line 458, in <module>
    kv , t , okbw = KDE(l_f_8_soi_ms[i])

  File "/home/azare/groups/PrimNeu/Aryo/analysis/opt/KDE.py", line 133, in KDE
    y = y * len(spike_times)

UnboundLocalError: local variable 'y' referenced before assignment
```
The problematic input array :  
`np.array([425.36666667, 230.6       ,  35.86666667])`

While an array of only 3 elemtns is not realistic to be considered as data, this was running through a loop of hundreds of sessions, hence such input data is also imaginable.
The program stuck in the middle of a loop with the above error.

It seems to me that in this case, your while statement was never satisfied (not 'True') : 
https://github.com/shimazaki/AdaptiveKDE/blob/64a06962e18d59a950eee5026c4c30c943e93b5e/adaptivekde/sskernel.py#L109
Hence the program stepped out of the While loop without defining the inside parameters which were called later  =>  UnboundLocalError.

**Comment by Aryo-Zare** [comment]
I handled this exception in my own main program & this is resolved.
